[project]
name = "rhymek"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "lyricsgenius>=3.7.5",
    "numpy>=2.3.5",
    "pandas>=2.3.3",
    "scipy>=1.16.3",
    "streamlit>=1.51.0",
    "transformers>=4.57.3",
]
